image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: 12

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> package.json
  - flow-typed
  - '%USERPROFILE%\.electron'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - yarn

test_script:
  - yarn package-ci